version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: barber_db
    restart: always
    environment:
      POSTGRES_USER: barber_user
      POSTGRES_PASSWORD: barber_password
      POSTGRES_DB: barber_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
